
# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "mt_episode"

buffer_size: 5000

# update the target network every _ steps
target_update_interval: 80

# use the Q_Learner to train
agent_output_type: "q"
learner: "bc_learner"
double_q: True
mixer: 

name: "bc-r"

# agent type
agent: "mt_bcr"

# mac
mac: "mt_bcr_mac"

# params about observation decomposition
id_length: 4
max_agent: 15

# params about trans mixing network
entity_embed_dim: 64
attn_embed_dim: 8

head: 1
depth: 1
