# env config for the grid mpe task: Spread

env: "grid_mpe"

env_args:
  map_name: cn-2
  n_agents: 2            
  field_size: [6,6]      
  sight: 5               
  episode_limit: 50        
  reach_range: 2
  default_task: True
  task_id: 2
  # seed: 7

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000

# offline collection config
num_episodes_collected: 2000
offline_data_quality: "expert"
offline_data_folder: "dataset"
save_replay_buffer: True
stop_winrate: 0.0
